name: BuildMode
version: 0.1.2
description: Allows players to use Creative-like features for building in Survival Mode.
author: hadenpf
api-version: 1.14
api: [] # for some reason I needed to include this

main: com.hadenfletcher.BuildMode.BuildMode
database: false
load: POSTWORLD

commands:
  buildmode:
    description: Enter and exit Build Mode.
    aliases: [bm, buildermode, build]
    usage: <command> [enable|disable]

permissions:
  buildmode.*:
    description: Allows use of all Build Mode features.
    default: op
  buildmode.use:
    description: Allows use of Build Mode.
    default: true
  buildmode.fly:
    description: Allows flight while in Build Mode.
    default: true
  buildmode.instabreak:
    description: Allows instant breaking of blocks while in Build Mode.
  buildmode.instabreak.bedrock:
    description: Allows breaking bedrock in Build Mode.
    default: true
  buildmode.set:
    description: Allows individual configuration of Build Mode features.
    default: true
  buildmode.set.fly:
    description: Allows individual toggling of Build Mode flight.
  buildmode.set.instabreak:
    description: Allows individual toggling of Build Mode instant breaking.
